version: '3'

services:
  etcd-1:
    container_name: etcd-1
    image: nearform/etcd
    command:
      - "/bin/sh"
      - "-ecx"
      - |
        etcd --name etcd-1 \
          --initial-advertise-peer-urls https://etcd-1:2380 \
          --listen-peer-urls https://172.16.238.10:2380 \
          --listen-client-urls http://172.16.238.10:2379,http://127.0.0.1:2379 \
          --advertise-client-urls http://etcd-1:2379 \
          --initial-cluster etcd-1=https://etcd-1:2380,etcd-2=https://etcd-2:2380,etcd-3=https://etcd-3:2380 \
          --peer-auto-tls \
          --data-dir /etcd/default.etcd \
          --initial-cluster-state new
    networks:
      etcd_net:
        ipv4_address: 172.16.238.10
    ports:
      - 2379
      - 2380
    expose:
      - "2379"
    volumes:
      - /etcd
  etcd-2:
    container_name: etcd-2
    image: nearform/etcd
    command:
      - "/bin/sh"
      - "-ecx"
      - |
        etcd --name etcd-2 \
          --initial-advertise-peer-urls https://etcd-2:2380 \
          --listen-peer-urls https://172.16.238.11:2380 \
          --listen-client-urls http://172.16.238.11:2379,http://127.0.0.1:2379 \
          --advertise-client-urls http://etcd-2:2379 \
          --initial-cluster etcd-1=https://etcd-1:2380,etcd-2=https://etcd-2:2380,etcd-3=https://etcd-3:2380 \
          --peer-auto-tls \
          --data-dir /etcd/default.etcd \
          --initial-cluster-state new
    networks:
      etcd_net:
        ipv4_address: 172.16.238.11
    ports:
      - 2379
      - 2380
    expose:
      - "2379"
    volumes:
      - /etcd
  etcd-3:
    container_name: etcd-3
    image: nearform/etcd
    command:
      - "/bin/sh"
      - "-ecx"
      - |
        etcd --name etcd-3 \
          --initial-advertise-peer-urls https://etcd-3:2380 \
          --listen-peer-urls https://172.16.238.12:2380 \
          --listen-client-urls http://172.16.238.12:2379,http://127.0.0.1:2379 \
          --advertise-client-urls http://etcd-3:2379 \
          --initial-cluster etcd-1=https://etcd-1:2380,etcd-2=https://etcd-2:2380,etcd-3=https://etcd-3:2380 \
          --peer-auto-tls \
          --data-dir /etcd/default.etcd \
          --debug \
          --initial-cluster-state new
    ports:
      - 2379
      - 2380
    networks:
      etcd_net:
        ipv4_address: 172.16.238.12
    expose:
      - "2379"
    volumes:
      - /etcd
networks:
  etcd_net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.238.0/24